<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>offline_speech_to_text</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableTopLevelStatements>false</EnableTopLevelStatements>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vosk" Version="0.3.38" />
    <PackageReference Include="NAudio" Version="2.1.0" />
  </ItemGroup>

</Project>
